name: Playwright CI

on:
  push:
    branches:
      - master  # Chạy khi có push lên nhánh chính
  pull_request:
    branches:
      - master  # Chạy khi có pull request vào nhánh chính

jobs:
  test:
    runs-on: ubuntu-latest  # Chạy trên môi trường Ubuntu (Linux)

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout mã nguồn từ repo

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Sử dụng Node.js phiên bản 16

    - name: Install dependencies
      run: |
        npm install  # Cài đặt các dependency

    - name: Install Playwright Browsers
      run: |
        npx playwright install  # Cài đặt các trình duyệt cần thiết

    - name: Run Playwright tests
      run: |
        npx playwright test  # Chạy các test của Playwright

        - name: Show trace
        if: failure()  # Chỉ hiển thị trace khi có lỗi
        run: |
          npx playwright show-trace trace.zip
      